// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// localTermsC
double localTermsC(NumericMatrix tab, IntegerVector nodes1, double mu, double sigma, double minbralen, int model, bool useRec);
RcppExport SEXP _BactDating_localTermsC(SEXP tabSEXP, SEXP nodes1SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP minbralenSEXP, SEXP modelSEXP, SEXP useRecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nodes1(nodes1SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type minbralen(minbralenSEXP);
    Rcpp::traits::input_parameter< int >::type model(modelSEXP);
    Rcpp::traits::input_parameter< bool >::type useRec(useRecSEXP);
    rcpp_result_gen = Rcpp::wrap(localTermsC(tab, nodes1, mu, sigma, minbralen, model, useRec));
    return rcpp_result_gen;
END_RCPP
}
// coalAlphaSumC
double coalAlphaSumC(NumericVector leaves, NumericVector nodes);
RcppExport SEXP _BactDating_coalAlphaSumC(SEXP leavesSEXP, SEXP nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type leaves(leavesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nodes(nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(coalAlphaSumC(leaves, nodes));
    return rcpp_result_gen;
END_RCPP
}
// coalDeltaC
double coalDeltaC(NumericVector leaves, NumericVector nodes, double alpha, double oldval, double newval);
RcppExport SEXP _BactDating_coalDeltaC(SEXP leavesSEXP, SEXP nodesSEXP, SEXP alphaSEXP, SEXP oldvalSEXP, SEXP newvalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type leaves(leavesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nodes(nodesSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type oldval(oldvalSEXP);
    Rcpp::traits::input_parameter< double >::type newval(newvalSEXP);
    rcpp_result_gen = Rcpp::wrap(coalDeltaC(leaves, nodes, alpha, oldval, newval));
    return rcpp_result_gen;
END_RCPP
}
// nodeDatesUpdateC
List nodeDatesUpdateC(NumericMatrix tab, int n, NumericVector orderedleafdates, NumericVector orderednodedates, NumericVector rn, double mu, double sigma, double l, double p, double alpha, double minbralen, double sdDates, int outerit, bool tuning, bool useCoalPrior, int model, bool useRec);
RcppExport SEXP _BactDating_nodeDatesUpdateC(SEXP tabSEXP, SEXP nSEXP, SEXP orderedleafdatesSEXP, SEXP orderednodedatesSEXP, SEXP rnSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP lSEXP, SEXP pSEXP, SEXP alphaSEXP, SEXP minbralenSEXP, SEXP sdDatesSEXP, SEXP outeritSEXP, SEXP tuningSEXP, SEXP useCoalPriorSEXP, SEXP modelSEXP, SEXP useRecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type orderedleafdates(orderedleafdatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type orderednodedates(orderednodedatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rn(rnSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type minbralen(minbralenSEXP);
    Rcpp::traits::input_parameter< double >::type sdDates(sdDatesSEXP);
    Rcpp::traits::input_parameter< int >::type outerit(outeritSEXP);
    Rcpp::traits::input_parameter< bool >::type tuning(tuningSEXP);
    Rcpp::traits::input_parameter< bool >::type useCoalPrior(useCoalPriorSEXP);
    Rcpp::traits::input_parameter< int >::type model(modelSEXP);
    Rcpp::traits::input_parameter< bool >::type useRec(useRecSEXP);
    rcpp_result_gen = Rcpp::wrap(nodeDatesUpdateC(tab, n, orderedleafdates, orderednodedates, rn, mu, sigma, l, p, alpha, minbralen, sdDates, outerit, tuning, useCoalPrior, model, useRec));
    return rcpp_result_gen;
END_RCPP
}
// coalpriorC
double coalpriorC(NumericVector leaves, NumericVector nodes, double alpha);
RcppExport SEXP _BactDating_coalpriorC(SEXP leavesSEXP, SEXP nodesSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type leaves(leavesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nodes(nodesSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(coalpriorC(leaves, nodes, alpha));
    return rcpp_result_gen;
END_RCPP
}
// likelihoodGammaC
double likelihoodGammaC(NumericMatrix tab, double mu);
RcppExport SEXP _BactDating_likelihoodGammaC(SEXP tabSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihoodGammaC(tab, mu));
    return rcpp_result_gen;
END_RCPP
}
// likelihoodRelaxedgammaC
double likelihoodRelaxedgammaC(NumericMatrix tab, double mu, double sigma);
RcppExport SEXP _BactDating_likelihoodRelaxedgammaC(SEXP tabSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihoodRelaxedgammaC(tab, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// likelihoodPoissonC
double likelihoodPoissonC(NumericMatrix tab, double mu);
RcppExport SEXP _BactDating_likelihoodPoissonC(SEXP tabSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihoodPoissonC(tab, mu));
    return rcpp_result_gen;
END_RCPP
}
// likelihoodNegbinC
double likelihoodNegbinC(NumericMatrix tab, double mu, double sigma);
RcppExport SEXP _BactDating_likelihoodNegbinC(SEXP tabSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihoodNegbinC(tab, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// changeinorderedvec
void changeinorderedvec(NumericVector vec, double old, double n);
RcppExport SEXP _BactDating_changeinorderedvec(SEXP vecSEXP, SEXP oldSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< double >::type old(oldSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    changeinorderedvec(vec, old, n);
    return R_NilValue;
END_RCPP
}
// likelihoodArcC
double likelihoodArcC(NumericMatrix tab, double mu, double sigma);
RcppExport SEXP _BactDating_likelihoodArcC(SEXP tabSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihoodArcC(tab, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// likelihoodCarcC
double likelihoodCarcC(NumericMatrix tab, double mu, double sigma);
RcppExport SEXP _BactDating_likelihoodCarcC(SEXP tabSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihoodCarcC(tab, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BactDating_localTermsC", (DL_FUNC) &_BactDating_localTermsC, 7},
    {"_BactDating_coalAlphaSumC", (DL_FUNC) &_BactDating_coalAlphaSumC, 2},
    {"_BactDating_coalDeltaC", (DL_FUNC) &_BactDating_coalDeltaC, 5},
    {"_BactDating_nodeDatesUpdateC", (DL_FUNC) &_BactDating_nodeDatesUpdateC, 17},
    {"_BactDating_coalpriorC", (DL_FUNC) &_BactDating_coalpriorC, 3},
    {"_BactDating_likelihoodGammaC", (DL_FUNC) &_BactDating_likelihoodGammaC, 2},
    {"_BactDating_likelihoodRelaxedgammaC", (DL_FUNC) &_BactDating_likelihoodRelaxedgammaC, 3},
    {"_BactDating_likelihoodPoissonC", (DL_FUNC) &_BactDating_likelihoodPoissonC, 2},
    {"_BactDating_likelihoodNegbinC", (DL_FUNC) &_BactDating_likelihoodNegbinC, 3},
    {"_BactDating_changeinorderedvec", (DL_FUNC) &_BactDating_changeinorderedvec, 3},
    {"_BactDating_likelihoodArcC", (DL_FUNC) &_BactDating_likelihoodArcC, 3},
    {"_BactDating_likelihoodCarcC", (DL_FUNC) &_BactDating_likelihoodCarcC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_BactDating(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
