# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

localTermsC <- function(tab, nodes1, mu, sigma, minbralen, model, useRec) {
    .Call('_BactDating_localTermsC', PACKAGE = 'BactDating', tab, nodes1, mu, sigma, minbralen, model, useRec)
}

fullLikC <- function(tab, mu, sigma, minbralen, model, useRec) {
    .Call('_BactDating_fullLikC', PACKAGE = 'BactDating', tab, mu, sigma, minbralen, model, useRec)
}

findCurrootC <- function(edge, rootchildren, rootnode) {
    .Call('_BactDating_findCurrootC', PACKAGE = 'BactDating', edge, rootchildren, rootnode)
}

coalAlphaSumC <- function(leaves, nodes) {
    .Call('_BactDating_coalAlphaSumC', PACKAGE = 'BactDating', leaves, nodes)
}

coalDeltaC <- function(leaves, nodes, alpha, oldval, newval) {
    .Call('_BactDating_coalDeltaC', PACKAGE = 'BactDating', leaves, nodes, alpha, oldval, newval)
}

nodeDatesUpdateC <- function(tab, n, orderedleafdates, orderednodedates, rn, mu, sigma, l, p, alpha, minbralen, sdDates, outerit, tuning, useCoalPrior, model, useRec, incrementalPrior) {
    .Call('_BactDating_nodeDatesUpdateC', PACKAGE = 'BactDating', tab, n, orderedleafdates, orderednodedates, rn, mu, sigma, l, p, alpha, minbralen, sdDates, outerit, tuning, useCoalPrior, model, useRec, incrementalPrior)
}

mcmcLoopC <- function(tab, edge, n, nbIts, thin, orderedleafdates, orderednodedates, misDates, rangedate, mu, sigma, alpha, l, p, sdMu, sdSigma, sdDates, updateMu, updateSigma, updateAlpha, updateRootAll, updateRootBranch, mixedModel, tuning, useCoalPrior, model, useRec, minbralen, mode, record) {
    .Call('_BactDating_mcmcLoopC', PACKAGE = 'BactDating', tab, edge, n, nbIts, thin, orderedleafdates, orderednodedates, misDates, rangedate, mu, sigma, alpha, l, p, sdMu, sdSigma, sdDates, updateMu, updateSigma, updateAlpha, updateRootAll, updateRootBranch, mixedModel, tuning, useCoalPrior, model, useRec, minbralen, mode, record)
}

coalpriorC <- function(leaves, nodes, alpha) {
    .Call('_BactDating_coalpriorC', PACKAGE = 'BactDating', leaves, nodes, alpha)
}

likelihoodGammaC <- function(tab, mu) {
    .Call('_BactDating_likelihoodGammaC', PACKAGE = 'BactDating', tab, mu)
}

likelihoodRelaxedgammaC <- function(tab, mu, sigma) {
    .Call('_BactDating_likelihoodRelaxedgammaC', PACKAGE = 'BactDating', tab, mu, sigma)
}

likelihoodPoissonC <- function(tab, mu) {
    .Call('_BactDating_likelihoodPoissonC', PACKAGE = 'BactDating', tab, mu)
}

likelihoodNegbinC <- function(tab, mu, sigma) {
    .Call('_BactDating_likelihoodNegbinC', PACKAGE = 'BactDating', tab, mu, sigma)
}

changeinorderedvec <- function(vec, old, n) {
    invisible(.Call('_BactDating_changeinorderedvec', PACKAGE = 'BactDating', vec, old, n))
}

likelihoodArcC <- function(tab, mu, sigma) {
    .Call('_BactDating_likelihoodArcC', PACKAGE = 'BactDating', tab, mu, sigma)
}

likelihoodCarcC <- function(tab, mu, sigma) {
    .Call('_BactDating_likelihoodCarcC', PACKAGE = 'BactDating', tab, mu, sigma)
}

